### ISSUE TITLE
ERROR after npm run dev

### ISSUE THREAD

**Issue by knjxz** [spektrummedia/nuxt-vue-multiselect#1]
Hi, I`m getting the following error..

![Captura de Tela 2019-04-23 às 15 36 42](https://user-images.githubusercontent.com/24529483/56607274-84670580-65de-11e9-87a0-874949beff24.png)

How can I solve this?

Thanks

**Comment by gabrielrobert** [comment]
@knjxz What's your nuxt version? It looks like a problem from nuxt 2.5.0 associated with core-js.

**Comment by knjxz** [comment]
@gabrielrobert I have updated to latest version (v2.7.0) and still getting the error

**Comment by gabrielrobert** [comment]
@knjxz Could you reproduce the problem using https://codepen.io and send me the link, please? Your errors seem unrelated to nuxt-vue-multiselect. Many thanks!

**Comment by knjxz** [comment]
@gabrielrobert The only thing I did was download the file, npm install and then npm run dev where I get the error. I didn`t touch the code yet..

**Comment by gabrielrobert** [comment]
@knjxz I solved it -> https://github.com/spektrummedia/nuxt-vue-multiselect/commit/2584b4bffdd7d128d34e8cda843f0f1ca373bcd9
