### ISSUE TITLE
CSS not loading on production

### ISSUE THREAD

**Issue by santicros** [spektrummedia/nuxt-vue-multiselect#2]
Hello!

With the nuxt module when I build the project with npm run build, the css aren't showing.

Is it working properly for others?

**Comment by santicros** [comment]
I finally changed to Vue-Multiselect but had the same problem.

Now I've finally discovered it was because I'm also using TailwindCSS with the nuxt-tailwindcss plugin and the classes were deleted on the PurgueCSS.

What has finally worked has been adding to my nuxt.config.js in the PurgueCSS whitelistPatterns section a multiselect value (and also added the nuxt transitions, because didn't work on production):

``` javascript
export default {
  purgeCSS: {
    whitelistPatterns: [
      /-(leave|enter|appear)(|-(to|from|active))$/,
      /^(?!(|.*?:)cursor-move).+-move$/,
      /^nuxt-link(|-exact)-active$/,
      /multiselect/
    ]
  }
}
```

**Comment by soumilroy** [comment]
Thank you very much! As someone new to tailwind + purgecss, I was confused when other modules css had been stripped off during production. Now I got this fixed, thanks to your comment!
